export type BusinessUnitParams = {
  setTitleState: any;
  titleState: string;
  identificationTypes: object;
  timezoneIdName: string;
  dateFormatCode: string;
  customerPortalCoverURL: string;
  tenantUUID: string;
  businessUnitUUID: string;
  countryId: number;
  paymentValidationTime: string;
  phoneNumber: string;
  fileFaviconUrl: string;
  contactChannelPhone: string;
  timeFormat: string;
  paymentMethods: object;
  hasPaymentGateway: boolean;
  fileUrl: string;
  colorCode: string;
  id: number;
  filename: string;
  logoUrl: string;
  logoHorizontalUrl: string;
  name: string;
  contextUrl: string;
  contextUrlHome: string;
  contact_phone: string;
};
